const initialState = {
    matchData: {},
    tiles: {
        11: {row: 1, col: 1, tileColor: 'whiteTile', occupied: true, piece: 'R', pieceColor: 'white', pieceImage: 'R', active: false, occupied: true},
        12: {row: 1, col: 2, tileColor: 'blackTile', occupied: true, piece: 'Kn', pieceColor: 'white', pieceImage: 'Kn', active: false, occupied: true},
        13: {row: 1, col: 3, tileColor: 'whiteTile', occupied: true, piece: 'B', pieceColor: 'white', pieceImage: 'B', active: false, occupied: true},
        14: {row: 1, col: 4, tileColor: 'blackTile', occupied: true, piece: 'Q', pieceColor: 'white', pieceImage: 'Q', active: false, occupied: true},
        15: {row: 1, col: 5, tileColor: 'whiteTile', occupied: true, piece: 'K', pieceColor: 'white', pieceImage: 'K', active: false, occupied: true},
        16: {row: 1, col: 6, tileColor: 'blackTile', occupied: true, piece: 'B', pieceColor: 'white', pieceImage: 'B', active: false, occupied: true},
        17: {row: 1, col: 7, tileColor: 'whiteTile', occupied: true, piece: 'Kn', pieceColor: 'white', pieceImage: 'Kn', active: false, occupied: true},
        18: {row: 1, col: 8, tileColor: 'blackTile', occupied: true, piece: 'R', pieceColor: 'white', pieceImage: 'R', active: false, occupied: true},
        21: {row: 2, col: 1, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        22: {row: 2, col: 2, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        23: {row: 2, col: 3, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        24: {row: 2, col: 4, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        25: {row: 2, col: 5, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        26: {row: 2, col: 6, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        27: {row: 2, col: 7, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        28: {row: 2, col: 8, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'white', pieceImage: 'P', active: false, occupied: true},
        31: {row: 3, col: 1, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        32: {row: 3, col: 2, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        33: {row: 3, col: 3, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        34: {row: 3, col: 4, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        35: {row: 3, col: 5, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        36: {row: 3, col: 6, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        37: {row: 3, col: 7, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        38: {row: 3, col: 8, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        41: {row: 4, col: 1, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        42: {row: 4, col: 2, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        43: {row: 4, col: 3, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        44: {row: 4, col: 4, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        45: {row: 4, col: 5, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        46: {row: 4, col: 6, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        47: {row: 4, col: 7, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        48: {row: 4, col: 8, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        51: {row: 5, col: 1, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        52: {row: 5, col: 2, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        53: {row: 5, col: 3, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        54: {row: 5, col: 4, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        55: {row: 5, col: 5, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        56: {row: 5, col: 6, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        57: {row: 5, col: 7, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        58: {row: 5, col: 8, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        61: {row: 6, col: 1, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        62: {row: 6, col: 2, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        63: {row: 6, col: 3, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        64: {row: 6, col: 4, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        65: {row: 6, col: 5, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        66: {row: 6, col: 6, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        67: {row: 6, col: 7, tileColor: 'whiteTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        68: {row: 6, col: 8, tileColor: 'blackTile', occupied: false, piece: '', pieceColor: '', pieceImage: '', active: false, occupied: false},
        71: {row: 7, col: 1, tileColor: 'whiteTile', occupied: true, piece: 'R', pieceColor: 'black', pieceImage: 'R', active: false, occupied: true},
        72: {row: 7, col: 2, tileColor: 'blackTile', occupied: true, piece: 'Kn', pieceColor: 'black', pieceImage: 'Kn', active: false, occupied: true},
        73: {row: 7, col: 3, tileColor: 'whiteTile', occupied: true, piece: 'B', pieceColor: 'black', pieceImage: 'B', active: false, occupied: true},
        74: {row: 7, col: 4, tileColor: 'blackTile', occupied: true, piece: 'Q', pieceColor: 'black', pieceImage: 'Q', active: false, occupied: true},
        75: {row: 7, col: 5, tileColor: 'whiteTile', occupied: true, piece: 'K', pieceColor: 'black', pieceImage: 'K', active: false, occupied: true},
        76: {row: 7, col: 6, tileColor: 'blackTile', occupied: true, piece: 'B', pieceColor: 'black', pieceImage: 'B', active: false, occupied: true},
        77: {row: 7, col: 7, tileColor: 'whiteTile', occupied: true, piece: 'Kn', pieceColor: 'black', pieceImage: 'Kn', active: false, occupied: true},
        78: {row: 7, col: 8, tileColor: 'blackTile', occupied: true, piece: 'R', pieceColor: 'black', pieceImage: 'R', active: false, occupied: true},
        81: {row: 8, col: 1, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        82: {row: 8, col: 2, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        83: {row: 8, col: 3, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        84: {row: 8, col: 4, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        85: {row: 8, col: 5, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        86: {row: 8, col: 6, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        87: {row: 8, col: 7, tileColor: 'whiteTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true},
        88: {row: 8, col: 8, tileColor: 'blackTile', occupied: true, piece: 'P', pieceColor: 'black', pieceImage: 'P', active: false, occupied: true}
    }
}

export default function chessSetReducer(state = initialState, action) {
    switch (action.type) {
      default:
        return state;
    }
}